import = ["/home/nord/.config/alacritty/tokyo-night.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
vi_mode_style = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.166"

[font]
size = 12

[font.normal]
family = "Liberation Mono"

[scrolling]
history = 50000
multiplier = 3
